### PR TITLE
Plotly Map

### PR DESCRIPTION
**Pull request by anncalderon**
I decided to add another mapping function using plotly's interactive feature; which will allow us to zoom in on points that are in the water. I have identified 4 ocean points and 1 point that is in a stream just by visually inspecting the points.

### CODE REVIEW

**Comment by MKLau** [comment]
That sounds good. It would be great to add an automated detection routine to assign points to land classifications, as opposed to only visually assessing them. 

Something like:

1. Define boundaries by lat and long ranges, flag points outside range
2. Get land classification for each point, flag points in a non-sensical class
3. Check the GPS coordinates for each flagged point
4. Visually assess locations of flagged points
5. Use other information to correct positions
6. Possibly assign points that are within a fixed distance of a sensible land class a new GPS coordinate using the minimum Euclidean distance.

**Comment by anncalderon** [comment]
I think this is a good idea; I only did the visual inspection because we had few enough points that it wasn't going to take me long. On closer inspection, there are many water features as we zoom in (small lakes, ponds, streams, rivers, and other riparian areas or drainages). I'll see whats out there that might be able to automatically catch some of those water points.

**Comment by MKLau** [comment]
@anncalderon 

This is probably the database of land/water classification we should use.

https://water.usgs.gov/GIS/huc.html

**Comment by MKLau** [comment]
I have some time to fix some of these issues, so I'm going to accept this pull request. 

I also moved the relevant notes on data cleaning over to the issues on the HF organization.

**Pull request merged**
